### PR TITLE
Use prepend over chaining

### PR DESCRIPTION
**Pull request by 8398a7**
refs #3

### CODE REVIEW

**Comment by arthurnn** [comment]
Can someone merge this?
cc @dewski

**Comment by dewski** [comment]
@arthurnn I unfortunately am not a maintainer on this repo.

**Comment by tisba** [comment]
Is there something we can do to get this merged? /cc @8398a7

**Comment by meowsus** [comment]
@suranyami I understand that supporting software is time consuming. This gem is currently broken in Rails 5 and this PR remedies the issues. It needs a merge and a new version version cut to rubygems.org.

If you no longer wish to maintain this library I'd be more than happy to take it over. 

You have my github username and here is my rubygems.org account profile: https://rubygems.org/profiles/meowsus

Happy to help.

**Comment by CHTJonas** [comment]
@suranyami any chance of a merge and release? It's been two and a half years and would be great to get rid of `git: 'https://github.com/8398a7/peek-sidekiq.git'` from the Gemfile!

**Comment by 8398a7** [comment]
All I can do is publish a gem with the name `peek_sidekiq` ....
The naming convention is broken, but is there a demand?

**Comment by CHTJonas** [comment]
I currently have the following in my Gemfile which is OK and works so long as your fork doesn't disappear any time soon:
```ruby
gem 'peek-sidekiq', '~> 1.0', '>= 1.0.3', git: 'https://github.com/8398a7/peek-sidekiq.git'
```
I'm just hoping that the owner of the gem can merge and cut a release, but if not then yeah maybe?

**Comment by suranyami** [comment]
Hi, all. Sorry for the tardiness. Will push a release ASAP.

**Comment by suranyami** [comment]
New release pushed to rubygems.org.

**Pull request merged**
